export const data = [
  {
    id: "1",
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L2",
    iniciativas: [
      {
        id: "1",
        titulo: "Reduccion de Telecomunicaciones",
        estado_simplificado: "En proceso",
        gerencia: "Sistemas",
        area: "Sistemas",
        interlocutor: "Tatiana Naranjo",
        lider_sponsor: "Tatiana Naranjo",
        integrante_exop: "Girleza Muñoz",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "30/10/2020",
        fecha_termino_implementacion_l4: "10/2/2021",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "7.800",
        incluido_en_presupuesto: "No",
        incluido_en_wave: "Si",
        ultimo_comentario: "",
        descripcion:
          "Presentar ahorro en la rubro de comunicaciones a traves de un plan de fidelizacion con el proveedor MOVISTAR (Colombia Telecomunicaciones        ",
        requiere_it: "Si",
        en_captura: "No capturada",
        impacto_en_costo: "Bajo Capex",
        impacto_en_beneficios: "Bajo beneficio",
        impacto_en_plazos: "Mediano plazo",
        criticidad: "0",
        impacto_en_potencial: "Bajo potencial",
        ciudad_abreviada: "BOG",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "2,000.00",
        meta_por_pais: "900.000",
        dias_implementacion: "103",
        dias_l0_l4: "44237",
        fase_entregable: "L2(Validacion)",
        acta_reunion_l0: "Si",
        l1_identificacion: "Si",
        ev_procesos_criticos: "Si",
        caso_de_negocio: "Si",
        ppt_caso_de_negocio: "Si",
        l2_validacion: "Si",
        gantt: "No",
        edt: "No",
        matriz_raci: "No",
        acta_constitucion_de_proyecto: "No",
        planeacion: "No",
        control_de_costos: "No",
        acta_cierre_proyecto: "No",
        implementacion: "No",
        caso_de_negocio_actualizado: "No",
        a3: "No",
        l5_capturada: "No",
        acta_de_repaso: "No",
      },
      {
        id: "2",
        titulo: "Reduccion de Telecomunicaciones",
        estado_simplificado: "En proceso",
        gerencia: "Sistemas",
        area: "Sistemas",
        interlocutor: "Tatiana Naranjo",
        lider_sponsor: "Tatiana Naranjo",
        integrante_exop: "Girleza Muñoz",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "30/10/2020",
        fecha_termino_implementacion_l4: "10/2/2021",
        costos_proyectos: "",
        base: "46",
        objetivo: "",
        beneficios_recurrente_anual: "7.800",
        incluido_en_presupuesto: "No",
        incluido_en_wave: "Si",
        ultimo_comentario: "",
        descripcion:
          "Presentar ahorro en la rubro de comunicaciones a traves de un plan de fidelizacion con el proveedor MOVISTAR (Colombia Telecomunicaciones        ",
        requiere_it: "Si",
        en_captura: "No capturada",
        impacto_en_costo: "Bajo Capex",
        impacto_en_beneficios: "Bajo beneficio",
        impacto_en_plazos: "Mediano plazo",
        criticidad: "0",
        impacto_en_potencial: "Bajo potencial",
        ciudad_abreviada: "BOG",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "2,000.00",
        meta_por_pais: "900.000",
        dias_implementacion: "103",
        dias_l0_l4: "44237",
        fase_entregable: "L2(Validacion)",
        acta_reunion_l0: "Si",
        l1_identificacion: "Si",
        ev_procesos_criticos: "Si",
        caso_de_negocio: "Si",
        ppt_caso_de_negocio: "Si",
        l2_validacion: "Si",
        gantt: "No",
        edt: "No",
        matriz_raci: "No",
        acta_constitucion_de_proyecto: "No",
        planeacion: "No",
        control_de_costos: "No",
        acta_cierre_proyecto: "No",
        implementacion: "No",
        caso_de_negocio_actualizado: "No",
        a3: "No",
        l5_capturada: "No",
        acta_de_repaso: "No",
      },
    ],
  },
  {
    id: "2",
    titulo: "Optimización uso de Pallets - Import Chile",
    pais: "Chile",
    ciudad: "Santiago",
    anio: "2021",
    estado: "L0",
    iniciativas: [
      {
        id: "13424234",
        titulo: "Optimización uso de Pallets - Import Chile",
        estado_simplificado: "Idea",
        gerencia: "Operaciones",
        area: "Rampa",
        interlocutor: "Jose Sandoval",
        lider_sponsor: "Jose Sandoval",
        integrante_exop: "Diego Zamora",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "30/10/2020",
        fecha_termino_implementacion_l4: "10/2/2021",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "7.800",
        incluido_en_presupuesto: "No",
        incluido_en_wave: "Si",
        ultimo_comentario: "",
        descripcion:
          "Este proyecto es una acción en conjunto entre el área de Ground handling (Mtto) y la bodega de importaciones de AEROSAN Chile. El problema se genera cuando el taller de mtto requiere repuestos que son adquiridos afuera de Chile y estos son traidos por medio aéreo con aerolíneas que AEROSAN importaciones no tiene contrato. Esta acción genera que los elementos puedan llegar a las bodegas de DEPOCARGO o FAST AIR, realizando un cobro por almacenaje y manipulación. ",
        requiere_it: "Si",
        en_captura: "No capturada",
        impacto_en_costo: "Bajo Capex",
        impacto_en_beneficios: "Bajo beneficio",
        impacto_en_plazos: "Mediano plazo",
        criticidad: "0",
        impacto_en_potencial: "Bajo potencial",
        ciudad_abreviada: "BOG",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "2,000.00",
        meta_por_pais: "900.000",
        dias_implementacion: "103",
        dias_l0_l4: "44237",
        fase_entregable: "L2(Validacion)",
        acta_reunion_l0: "Si",
        l1_identificacion: "Si",
        ev_procesos_criticos: "Si",
        caso_de_negocio: "Si",
        ppt_caso_de_negocio: "Si",
        l2_validacion: "Si",
        gantt: "No",
        edt: "No",
        matriz_raci: "No",
        acta_constitucion_de_proyecto: "No",
        planeacion: "No",
        control_de_costos: "No",
        acta_cierre_proyecto: "No",
        implementacion: "No",
        caso_de_negocio_actualizado: "No",
        a3: "No",
        l5_capturada: "No",
        acta_de_repaso: "No",
      },
    ],
  },
];
