export const data = [
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L2",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L3",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "6",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
      {
        estado_simplificado: "Pausada",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "6",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L5",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "8",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L3",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "5",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L1",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "2",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L5",
    iniciativas: [],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L4",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "9",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L4",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "9",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L0",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },

      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L0",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "2",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "4",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L0",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "2",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L0",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "67",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
  {
    titulo: "Reduccion de Telecomunicaciones",
    pais: "Colombia",
    ciudad: "Bogota",
    anio: "2021",
    estado: "L1",
    iniciativas: [
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "67",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
      {
        estado_simplificado: "En proceso",
        gerencia: "",
        area: "",
        interlocutor: "",
        lider_sponsor: "",
        integrante_exop: "",
        fecha_incorporacion_cartera: "",
        fecha_inicio_implementacion_l3: "",
        fecha_termino_implementacion_l4: "",
        costos_proyectos: "",
        base: "67",
        objetivo: "",
        beneficios_recurrente_anual: "",
        incluido_en_presupuesto: "",
        incluido_en_wave: "",
        ultimo_comentario: "",
        descripcion: "",
        requiere_it: "",
        en_captura: "",
        impacto_en_costo: "",
        impacto_en_beneficios: "",
        impacto_en_plazos: "",
        criticidad: "",
        impacto_en_potencial: "",
        ciudad_abreviada: "",
        latitud: "",
        longitud: "",
        meta_beneficio_anio: "",
        meta_por_pais: "",
        dias_implementacion: "",
        dias_l0_l4: "",
        fase_entregable: "",
        acta_reunion_l0: "",
        l1_identificacion: "",
        ev_procesos_criticos: "",
        caso_de_negocio: "",
        ppt_caso_de_negocio: "",
        validacion: "",
        gantt: "",
        edt: "",
        matriz_raci: "",
        acta_constitucion_de_proyecto: "",
        planeacion: "",
        control_de_costos: "",
        acta_cierre_proyecto: "",
        implementacion: "",
        caso_de_negocio_actualizado: "",
        a3: "",
        l5_capturada: "",
        acta_de_repaso: "",
      },
    ],
  },
];
