export const dataList = [
  // {
  //   id: "1",
  //   titulo: "Reduccion de Telecomunicaciones",
  //   pais: "Colombia",
  //   ciudad: "Bogota",
  //   anio: "2021",
  //   estado: "L2",
  //   estado_simplificado: "En proceso",
  //   gerencia: "Sistemas",
  //   area: "Sistemas",
  //   interlocutor: "Tatiana Naranjo",
  //   lider_sponsor: "Tatiana Naranjo",
  //   integrante_exop: "Girleza Muñoz",
  //   fecha_incorporacion_cartera: "",
  //   fecha_inicio_implementacion_l3: "30/10/2020",
  //   fecha_termino_implementacion_l4: "10/2/2021",
  //   costos_proyectos: "",
  //   base: "4",
  //   objetivo: "",
  //   beneficios_recurrente_anual: "7.800",
  //   incluido_en_presupuesto: "No",
  //   incluido_en_wave: "Si",
  //   ultimo_comentario: "",
  //   descripcion:
  //     "Presentar ahorro en la rubro de comunicaciones a traves de un plan de fidelizacion con el proveedor MOVISTAR (Colombia Telecomunicaciones        ",
  //   requiere_it: "Si",
  //   en_captura: "No capturada",
  //   impacto_en_costo: "Bajo Capex",
  //   impacto_en_beneficios: "Bajo beneficio",
  //   impacto_en_plazos: "Mediano plazo",
  //   criticidad: "0",
  //   impacto_en_potencial: "Bajo potencial",
  //   ciudad_abreviada: "BOG",
  //   latitud: "",
  //   longitud: "",
  //   meta_beneficio_anio: "2,000.00",
  //   meta_por_pais: "900.000",
  //   dias_implementacion: "103",
  //   dias_l0_l4: "44237",
  //   fase_entregable: "L2(Validacion)",
  //   acta_reunion_l0: "Si",
  //   l1_identificacion: "Si",
  //   ev_procesos_criticos: "Si",
  //   caso_de_negocio: "Si",
  //   ppt_caso_de_negocio: "Si",
  //   l2_validacion: "Si",
  //   gantt: "No",
  //   edt: "No",
  //   matriz_raci: "No",
  //   acta_constitucion_de_proyecto: "No",
  //   planeacion: "No",
  //   control_de_costos: "No",
  //   acta_cierre_proyecto: "No",
  //   implementacion: "No",
  //   caso_de_negocio_actualizado: "No",
  //   a3: "No",
  //   l5_capturada: "No",
  //   acta_de_repaso: "No",
  // },
  {
    id: "002",
    titulo_iniciativa: "REDUCCIÓN TELECOMUNICACIONES 2223434",
    pais: "Colombia",
    ciudad: "Bogotá",
    anio: "2021",
    estado_wave: "L2",
    status: "En proceso",
    gerencia: "Sistemas",
    area: "Sistemas",
    cliente_interno: "Tatiana Naranjo",
    sponsor: "Tatiana Naranjo",
    ingeniero_exop: "Girleza Muñoz",
    fecha_inicio_implementacion: "10/30/20",
    fecha_termino_implementacion_comprometida: "2/10/21",
    beneficio_recurrente_anual_comprometido: "7.800",
    beneficio_recurrente_anual_proyectado: "7.400",
    en_presupuesto: "No",
    incluido_wave: "Si",
    descripcion:
      "Presentar ahorro en la rubro de comunicaciones a traves de un plan de fidelizacion con el proveedor MOVISTAR (Colombia Telecomunicaciones)\r\r\nCon este proyecto de ahorro se trabajo en una propuesta de fidelización, actualizando los planes existentes  a planes básicos. \r\r\nDebido al Covid 19 esta propuesta no se puedo llevar en el año 2020, por tanto el beneficio se traslada al año 2021.\r\r\nEste ahorro fue proyectado sobre 129 líneas corporativas, en su modalidad de cargo básico\r\r\n",
    requiere_it: "Si",
    en_captura: "No Capturada",
    beneficio_capturado: "0",
    aux_impacto_capex: "Bajo Capex",
    aux_impacto_beneficio: "Bajo Beneficio",
    aux_impacto_plazo: "Mediano Plazo",
    criticidad: "0",
    impacto_potencial: "Bajo Potencial",
    ciudad_abreviada: "BOG",
    latitud: "4.701389",
    longitud: "-74.146944",
    meta_beneficio_año: "2,000,000",
    meta_pais: "900,000",
    dias_implementacion: "103",
    dias_total: "44237",
    aux_beneficio: "2",
    fase_entregable: "L2 (Validación)",
    l0_idea: "Si",
    acta_reunion_1: "Si",
    l1_Identificacion: "Si",
    ev_procesos_criticos_2: "Si",
    caso_de_negocio_3: "Si",
    ppt_caso_de_negocio_4: "Si",
    l2_validacion: "Si",
    gantt_5: "No",
    edt_6: "No",
    matriz_raci_7: "No",
    acta_constitucion_de_proyecto_8: "No",
    l3_planeacion: "No",
    control_de_costos_9: "No",
    acta_cierre_proyecto_10: "No",
    l4_implementacion: "No",
    caso_de_negocio_actualizado_11: "No",
    a3_12: "No",
    l5_capturada: "No",
    acta_de_traspaso_13: "No",
  },
  {
    id: "005",
    titulo_iniciativa: "REDUCCIÓN TELECOMUNICACIONES",
    pais: "Colombia",
    ciudad: "Bogotá",
    anio: "2021",
    estado_wave: "L2",
    status: "En proceso",
    gerencia: "Sistemas",
    area: "Sistemas",
    cliente_interno: "Tatiana Naranjo",
    sponsor: "Tatiana Naranjo",
    ingeniero_exop: "Girleza Muñoz",
    fecha_inicio_implementacion: "1/30/20",
    fecha_termino_implementacion_comprometida: "2/10/21",
    beneficio_recurrente_anual_comprometido: "7.800",
    beneficio_recurrente_anual_proyectado: "7.400",
    en_presupuesto: "No",
    incluido_wave: "Si",
    descripcion:
      "Presentar ahorro en la rubro de comunicaciones a traves de un plan de fidelizacion con el proveedor MOVISTAR (Colombia Telecomunicaciones)\r\r\nCon este proyecto de ahorro se trabajo en una propuesta de fidelización, actualizando los planes existentes  a planes básicos. \r\r\nDebido al Covid 19 esta propuesta no se puedo llevar en el año 2020, por tanto el beneficio se traslada al año 2021.\r\r\nEste ahorro fue proyectado sobre 129 líneas corporativas, en su modalidad de cargo básico\r\r\n",
    requiere_it: "Si",
    en_captura: "No Capturada",
    beneficio_capturado: "0",
    aux_impacto_capex: "Bajo Capex",
    aux_impacto_beneficio: "Bajo Beneficio",
    aux_impacto_plazo: "Mediano Plazo",
    criticidad: "0",
    impacto_potencial: "Bajo Potencial",
    ciudad_abreviada: "BOG",
    latitud: "4.701389",
    longitud: "-74.146944",
    meta_beneficio_año: "2,000,000",
    meta_pais: "900,000",
    dias_implementacion: "103",
    dias_total: "44237",
    aux_beneficio: "2",
    fase_entregable: "L2 (Validación)",
    l0_idea: "Si",
    acta_reunion_1: "Si",
    l1_Identificacion: "Si",
    ev_procesos_criticos_2: "Si",
    caso_de_negocio_3: "Si",
    ppt_caso_de_negocio_4: "Si",
    l2_validacion: "Si",
    gantt_5: "No",
    edt_6: "No",
    matriz_raci_7: "No",
    acta_constitucion_de_proyecto_8: "No",
    l3_planeacion: "No",
    control_de_costos_9: "No",
    acta_cierre_proyecto_10: "No",
    l4_implementacion: "No",
    caso_de_negocio_actualizado_11: "No",
    a3_12: "No",
    l5_capturada: "No",
    acta_de_traspaso_13: "No",
  },
];
